name: xyz_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_sign_in: ^6.1.5
  firebase_core: ^2.21.0
  image_picker: ^1.0.4
  firebase_storage: ^11.4.1
  dio: ^5.3.3
  intl: ^0.18.1
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  cloud_firestore: ^4.13.3
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/